## date: 2026-04-14 10:08:13

# use `Include ~/workspace/build_env/ai2-robot/.env/template/ssh.conf`

Host woosh
  HostName 169.254.128.2
  User woosh
  #password wooshrobot
  Port 22
  ServerAliveInterval 30
  ServerAliveCountMax 100
  TCPKeepAlive yes
  SendEnv ENTRY_CONTAINER

Host orin
  HostName 169.254.128.100
  User robot
  Port 22
  ServerAliveInterval 30
  ServerAliveCountMax 100
  TCPKeepAlive yes
  SendEnv ENTRY_CONTAINER
