# https://colcon.readthedocs.io/en/released/user/using-multiple-workspaces.html
# export COLCON_DEFAULTS_FILE=/workspaces/cream_ws/defaults.yaml
build:
  packages-select:
    # - quadruped
  cmake-args:
    - -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - -DCMAKE_BUILD_TYPE=Debug
    - -Wall
    - -Wextra
    - -Wpedantic
    # - --trace
    # - --debug-find
  # https://colcon.readthedocs.io/en/released/user/configuration.html#meta-files
  # metas:
  #   - /config/colcon.meta
  cmake-force-configure: true
  symlink-install: true
  merge-install: false
  parallel-workers: 15
  event-handlers:
    - console_direct+
    - console_cohesion+
    - console_package_list+

log-level:
  - info
