export http_proxy=http://192.168.31.201:7891
export https_proxy=http://192.168.31.201:7891

export PATH=.:${HOME}/.local/bin:$PATH

# set workdir
export MACHINE=vmware
export ROS_DISTRO=humble
export AGV_WORKDIR=replace_to_script_path

source ${AGV_WORKDIR}/.env/bashrc.bash
source ${AGV_WORKDIR}/.env/system.bash
source ${AGV_WORKDIR}/.env/robot.bash
