Host repos.nas
  HostName @SETUP_NAS_HOST@
  User @SETUP_NAS_USER@
  Port @SETUP_NAS_PORT@
  ServerAliveInterval 30
  ServerAliveCountMax 100
  TCPKeepAlive yes

Host repos.local repos
  HostName @SETUP_REPOS_HOST@
  User @SETUP_SSH_USER@
  Port 22
  ServerAliveInterval 30
  ServerAliveCountMax 100
  TCPKeepAlive yes

Host nas
  HostName @SETUP_NAS_HOST@
  User @SETUP_NAS_USER@
  Port @SETUP_NAS_PORT@
  ServerAliveInterval 30
  ServerAliveCountMax 100
  TCPKeepAlive yes
  ForwardX11 yes
  ForwardX11Trusted yes
